apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: order-processor-scaler
  labels:
    app: order-processor
    deploymentName: order-processor
spec:
  scaleTargetRef:
    deploymentName: order-processor
  minReplicaCount: 0    #Change to define how many minimum replicas you want
  maxReplicaCount: 15
  pollingInterval: 10    # Optional. Default: 30 seconds
  cooldownPeriod:  30   # Optional. Default: 300 seconds
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      connection: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
      queueLength: '5'