apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: jakobehn/keda-sample-dotnet-worker-servicebus-queue
        env:
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: secrets-order-consumer
             key: servicebus-connectionstring
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-consumer
  labels:
    app: order-processor
data:
  servicebus-connectionstring: RW5kcG9pbnQ9c2I6Ly9rZWRhc2Iuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1vcmRlci1jb25zdW1lcjtTaGFyZWRBY2Nlc3NLZXk9ckJZdzU3YkpqUFQ0QnFmZlg5SWxCTkU3OEJGM1VFejU0TTJjV0RsTjcyMD07RW50aXR5UGF0aD1vcmRlcnMK