version: '3.4'

services:
  kedasampleweb:
    image: jakobehn/keda-sample-dotnet-web
    build:
      context: .
      dockerfile: Keda.Samples.DotNet.Web/Dockerfile
    environment:
      - OrderQueue__ConnectionString=<CHANGETHIS>

  kedasampleorderprocessor:
    image: jakobehn/keda-sample-dotnet-worker-servicebus-queue
    build:
      context: .
      dockerfile: Keda.Samples.Dotnet.OrderProcessor/Dockerfile
    environment:
      - KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING=<CHANGETHIS>
      - KEDA_SAMPLEWEB_URL=http://kedasampleweb

